//
// Created by mushan on 24/2/22.
//

#ifndef MY_PROJECT_CONFIG_H
#define MY_PROJECT_CONFIG_H

#define DEBUG_MODE true


#define SERVER_PORT 5421
#define SERVER_TIMEOUT 60000
#define SERVER_LOG_LEVEL -1
#define SERVER_REACTOR_BACKLOG 128
#define SERVER_USE_LOGGER true
#define SERVER_USE_ELEG_DISCONNECT true
#define SERVER_RESOURCE_DIR  "./data/"


#define BLOCKING_QUEUE_LENGTH 1000


#define BUFFER_SIZE 1000
#define BUFFER_EXTEND_RATIO 1.5
#define BUFFER_FD_READER_BUFFER_SIZE 5000


#define LOGGER_PATH "./log"
#define LOGGER_LEVEL 0;
#define LOGGER_QUEUE_CAPACITY 1000
#define LOGGER_FILE_NAME_MAX_LEN 1000
#define LOGGER_FILE_SUFFIX ".log"



#define TIMER_HEAP_SIZE  100


#define THREAD_POOL_THREAD_NUM  20






#define EPOLL_LENGTH 1000
#define EPOLL_MAX_EVENTS_LENGTH 128
#define EPOLL_TRIGGER_METHOD "ET"
#define EPOLL_TIME_OUT -1



#define DEBUGCOUT(str) std::cout<<str<<std::endl;

#endif //MY_PROJECT_CONFIG_H
